import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/app_providers.dart';

/// Static lookup of translated strings, keyed by language name.
///
/// Missing keys in a non-English language fall back to English so the UI
/// never shows a raw key. Languages other than English / Pidgin / Igbo
/// rely on the fallback for keys that aren't translated yet.
class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'English': _en,
    'Pidgin': _pcm,
    'Igbo': _ig,
    'Yoruba': _yo,
    'Hausa': _ha,
  };

  static String translate(String key, String language) {
    final dict = _localizedValues[language];
    if (dict != null && dict.containsKey(key)) return dict[key]!;
    final fallback = _localizedValues['English'];
    if (fallback != null && fallback.containsKey(key)) return fallback[key]!;
    return key;
  }
}

/// `ref.tr('key')` from a ConsumerWidget/ConsumerState.
/// Watches `languageProvider` so widgets rebuild on language change.
extension TrRef on WidgetRef {
  String tr(String key) => AppLocalizations.translate(key, watch(languageProvider));
}

/// `context.tr('key', ref)` for places that have a context but no ref.
/// Prefer `ref.tr(...)` when possible.
extension TrContext on BuildContext {
  String trWith(WidgetRef ref, String key) =>
      AppLocalizations.translate(key, ref.read(languageProvider));
}

// ---------------------------------------------------------------------------
// English (source of truth)
// ---------------------------------------------------------------------------
const Map<String, String> _en = {
  // App-wide
  'app_title': 'MartoraX',
  'tagline': 'Your City In Your Pocket',
  'continue': 'Continue',
  'continue_btn': 'Continue',
  'back': 'Back',
  'next': 'Next',
  'skip': 'Skip',
  'cancel': 'Cancel',
  'save': 'Save',
  'done': 'Done',
  'retry': 'Retry',
  'loading': 'Loading...',
  'or_continue_with': 'Or continue with',

  // Bottom nav
  'home': 'Home',
  'search': 'Search',
  'bookings': 'Bookings',
  'profile': 'Profile',
  'cart': 'Cart',

  // Onboarding (Get Started)
  'gs_title': 'Ready to Explore?',
  'gs_subtitle_prefix': 'Join thousands of residents buying products and booking services in ',
  'gs_subtitle_suffix': ' today.',
  'gs_city': 'Asaba',
  'gs_start_shopping': 'Start Shopping',
  'gs_register_vendor': 'Register as a Vendor',
  'gs_register_provider': 'Register as a Service Provider',
  'gs_already_have_account': 'Already have an account? ',
  'gs_log_in': 'Log In',

  // Language selection
  'lang_title': 'Choose your language',
  'lang_subtitle': "Experience MartoraX in the language\nyou're most comfortable with.",
  'lang_select_appbar': 'Select Language',

  // Role selection
  'role_title': 'How would you like\nto join?',
  'role_subtitle': 'Select the account type that best\ndescribes your needs in Asaba.',
  'role_shopper': 'Shopper',
  'role_shopper_desc': 'I want to buy products and book services',
  'role_vendor': 'Vendor',
  'role_vendor_desc': 'I want to sell products',
  'role_provider': 'Service Provider',
  'role_provider_desc': 'I want to offer my professional skills',
  'role_rider': 'Rider',
  'role_rider_desc': 'I want to deliver and earn',

  // Login
  'login_welcome': 'Welcome Back',
  'login_subtitle': 'Login to your MartoraX account',
  'login_email': 'Email',
  'login_email_hint': 'name@example.com',
  'login_password': 'Password',
  'login_password_hint': 'Enter password',
  'login_forgot': 'Forgot Password?',
  'login_btn': 'Login',
  'login_no_account': "Don't have an account? ",
  'login_create_account': 'Create an account',
  'login_enter_creds': 'Enter email and password',
  'login_failed': 'Login failed. Check your connection.',

  // Register
  'reg_title': 'Create Your Account',
  'reg_subtitle': 'Join MartoraX to shop and book services in Asaba.',
  'reg_full_name': 'Full Name',
  'reg_full_name_hint': 'John Doe',
  'reg_phone': 'Phone Number',
  'reg_btn': 'Sign Up',
  'reg_required': 'Name, email, and password are required',
  'reg_password_short': 'Password must be at least 6 characters',
  'reg_success': 'Account created! Check your email to verify.',
  'reg_failed': 'Signup failed. Check your connection.',
  'reg_already_have_account': 'Already have an account? ',
  'reg_login': 'Log In',

  // Home
  'location_label': 'YOUR LOCATION',
  'location_value': 'Asaba, Delta State',
  'search_placeholder': 'Search markets or services...',
  'market_clusters': 'Market Clusters',
  'see_all': 'See All',
  'market_price_board': 'MARKET PRICE BOARD',
  'updated_today': 'Updated Today, 8:00 AM',
  'quick_services': 'Quick Services',
  'hot_deals': 'Hot Deals',
  'live': 'LIVE',

  // Cart
  'cart_title': 'My Cart',
  'cart_empty_title': 'Your cart is empty',
  'cart_empty_subtitle': 'Add products from any vendor to get started.',
  'cart_start_shopping': 'Start Shopping',
  'cart_clear': 'Clear cart',
  'cart_payment_summary': 'Payment Summary',
  'cart_items_total': 'Items Total',
  'cart_delivery_fee': 'Delivery Fee',
  'cart_safepay_fee': 'SafePay Fee',
  'cart_total': 'Total',
  'cart_checkout_btn': 'Proceed to Checkout',
  'cart_added_suffix': ' added to cart',
  'cart_view': 'VIEW CART',

  // Profile
  'profile_title': 'Profile',
  'profile_preferences': 'PREFERENCES',
  'profile_language': 'Language',
  'profile_language_sub': 'English, Pidgin, Igbo...',
  'profile_notifications': 'Notifications',
  'profile_theme': 'App Theme',
  'profile_logout': 'Logout',

  // SafePay
  'safepay_protection': 'SafePay Protection',
  'safepay_held_msg': 'SafePay holds your money for 48 hours for resolution. Your funds are secure while we investigate.',
  'confirm_release': 'Confirm Release',
  'raise_dispute': 'Raise Dispute',
  'raise_issue': 'Raise an Issue',
  'details_optional': 'Additional details (Optional)',
  'what_is_problem': 'What is the problem?',
  'upload_evidence': 'Upload Evidence',
  'evidence_hint': 'Include photos or videos showing the issue for faster resolution.',

  // Screen titles (st_*)
  'st_admin_escrow': 'Escrow Dashboard',
  'st_admin_universal': 'Universal Dashboard',
  'st_ai_feed': 'AI Personalized Feed',
  'st_ai_concierge': 'Service Concierge',
  'st_ai_smart_quote': 'New Quote',
  'st_bookings': 'My Bookings',
  'st_checkout_confirm': 'Checkout',
  'st_checkout_delivery': 'Delivery Details',
  'st_checkout_payment': 'Payment Method',
  'st_order_confirm': 'Confirmation',
  'st_group_buy_create': 'Create Group Buy Deal',
  'st_group_buy_invite': 'Group Buy Invite',
  'st_live_deals': 'Live Deals',
  'st_market_cluster': 'Market Cluster',
  'st_market_hubs': 'Market Hubs',
  'st_market_trends': 'Market Trends',
  'st_notifications': 'Notifications',
  'st_delivery_success': 'Delivery Success',
  'st_delivery_tracking': 'Order Tracking',
  'st_delivery_safety': 'Delivery Safety',
  'st_order_status': 'Order Status',
  'st_order_receipt': 'Receipt Preview',
  'st_product_details': 'Product Details',
  'st_provider_leads': 'My Leads',
  'st_provider_nearby': 'Nearby Services',
  'st_provider_chat': 'Chat',
  'st_provider_dashboard': 'Provider Dashboard',
  'st_provider_kyc': 'Verify Your Identity',
  'st_provider_register': 'Register as Provider',
  'st_service_profile': 'Service Profile',
  'st_service_booking': 'Book Service',
  'st_service_discovery': 'Discover Services',
  'st_provider_portfolio': 'Provider Portfolio',
  'st_quote_approval': 'Service Quote',
  'st_rider_earnings': 'Earnings',
  'st_rider_in_transit': 'In Transit',
  'st_rider_register': 'Join as a Rider',
  'st_rider_dashboard': 'Rider Dashboard',
  'st_rider_discovery': 'Find a Rider',
  'st_search_filters': 'Filters',
  'st_search': 'Search',
  'st_vendor_catalog': 'Basic Details',
  'st_vendor_dashboard': 'Vendor Dashboard',
  'st_vendor_go_live': 'Go Live Setup',
  'st_vendor_inventory': 'Inventory',
  'st_vendor_kyc': 'Verify Your Stall',
  'st_vendor_location': 'Store Location',
  'st_vendor_orders': 'Orders',
  'st_vendor_order_details': 'Order Details',
  'st_vendor_register': 'Register as Vendor',
  'st_vendor_analytics': 'Sales Analytics',
  'st_escrow_dispute': 'Raise Dispute',
  'st_wallet_history': 'History & Statements',
  'st_wallet_link_bank': 'Link Bank Account',
  'st_wallet': 'Wallet & Cashback',
  'st_release_funds': 'Release Funds',
  'st_delivery_rating': 'Rate Delivery',
  'st_product_bargain': 'Send a Bargain',
  'st_onboarding': 'Welcome',

  // Splash
  'splash_connecting': 'CONNECTING TO ASABA',

  // Onboarding slides
  'onb_slide1_title': 'Find Everything\nin Asaba',
  'onb_slide1_sub': 'From Ogbogonogo Main Market to your doorstep. Trusted vendors at your fingertips.',
  'onb_slide2_title': 'Find Expert Services\nNearby',
  'onb_slide2_sub': 'From skilled plumbers to professional makeup artists. Book trusted experts in Asaba with confidence.',
  'onb_slide3_title': 'Fast Delivery &\nSafe Payments',
  'onb_slide3_sub': 'SafePay holds your money until delivery. Get your order tracked live from vendor to your door.',

  // Search deeper
  'search_filter_nearest': 'Nearest',
  'search_filter_open': 'Open Now',
  'search_filter_cheap': 'Cheapest',
  'search_filter_trusted': 'Trusted',
  'search_tab_vendors': 'Vendors',
  'search_tab_services': 'Services',
  'search_tab_markets': 'Markets',
  'search_list': 'List',
  'search_map': 'Map',
  'search_visit_store': 'Visit Store',
  'search_map_view': 'Map View',
  'search_map_coming': 'Google Maps integration coming soon',

  // Bookings deeper
  'bk_tab_upcoming': 'Upcoming',
  'bk_tab_completed': 'Completed',
  'bk_tab_cancelled': 'Cancelled',
  'bk_empty': 'No bookings yet',

  // Checkout deeper
  'co_delivery_method': 'Delivery Method',
  'co_home_delivery': 'Home Delivery',
  'co_market_pickup': 'Market Pickup',
  'co_address': 'Delivery Address',
  'co_address_hint': 'House no., street, area',
  'co_instructions': 'Delivery Instructions (Optional)',
  'co_instructions_hint': 'Apartment, landmark, gate code...',
  'co_continue_to_pay': 'Continue to Payment',
  'co_pay_card': 'Card',
  'co_pay_transfer': 'Bank Transfer',
  'co_pay_wallet': 'Wallet',
  'co_pay_continue': 'Continue',
  'co_order_summary': 'Order Summary',
  'co_place_order': 'Place Order',
  'co_payment_protected': 'Payment Protected by SafePay',
  'co_confirmation_title': 'Order Placed!',
  'co_confirmation_sub': 'Your order is being processed. We will notify you with updates.',
  'co_track_order': 'Track Order',
  'co_continue_shopping': 'Continue Shopping',

  // Orders / tracking deeper
  'ord_status_placed': 'Order Placed',
  'ord_status_preparing': 'Preparing',
  'ord_status_shipped': 'Shipped',
  'ord_status_delivered': 'Delivered',
  'ord_in_progress': 'In Progress',
  'ord_track_live': 'Live Tracking',
  'ord_call_rider': 'Call Rider',
  'ord_chat_rider': 'Chat Rider',
  'ord_eta': 'Estimated Arrival',
  'ord_delivered_title': 'Order Delivered!',
  'ord_rate_vendor': 'Rate Vendor',
  'ord_rate_rider': 'Rate Rider',
  'ord_tip_rider': 'Tip Rider',
  'ord_leave_review': 'Leave a Review',

  // Wallet deeper
  'wal_balance': 'Wallet Balance',
  'wal_topup': 'Top Up',
  'wal_withdraw': 'Withdraw',
  'wal_history': 'Transaction History',
  'wal_recent': 'Recent Activity',
  'wal_cashback': 'Cashback Earned',
  'wal_promo_hint': 'Enter promo code',
  'wal_apply': 'Apply',

  // Notifications deeper
  'ntf_mark_all_read': 'Mark all as read',
  'ntf_empty': "You're all caught up",

  // Product detail deeper
  'pd_quantity': 'Quantity',
  'pd_description': 'Product Description',
  'pd_bargain': 'Bargain',
  'pd_add_to_cart': 'Add to Cart',
  'pd_visit_shop': 'Visit Shop',
  'pd_trusted': 'TRUSTED',

  // Profile deeper
  'prof_my_orders': 'My Orders',
  'prof_saved_addresses': 'Saved Addresses',
  'prof_payment_methods': 'Payment Methods',
  'prof_account': 'ACCOUNT',
  'prof_support': 'SUPPORT',
  'prof_help_center': 'Help Center',
  'prof_contact_support': 'Contact Support',
  'prof_terms': 'Terms & Privacy',
  'prof_become_vendor': 'Become a Vendor or\nService Provider',
  'prof_become_sub': 'Start selling or offer services in Asaba',
  'prof_get_started': 'Get Started',

  // Common action buttons used across many screens
  'btn_submit': 'Submit',
  'btn_save': 'Save',
  'btn_save_changes': 'Save Changes',
  'btn_confirm': 'Confirm',
  'btn_go_back': 'Go Back',
  'btn_get_started': 'Get Started',
  'btn_proceed': 'Proceed',
  'btn_pay_now': 'Pay Now',
  'btn_go_live': 'Go Live',
  'btn_add_product': 'Add Product',
  'btn_submit_review': 'Submit Review',
  'btn_send': 'Send',
  'btn_book_now': 'Book Now',
  'btn_accept': 'Accept',
  'btn_reject': 'Reject',
};

// ---------------------------------------------------------------------------
// Naija Pidgin
// ---------------------------------------------------------------------------
const Map<String, String> _pcm = {
  'app_title': 'MartoraX',
  'tagline': 'Your City For Your Pocket',
  'continue': 'Kontinu',
  'continue_btn': 'Kontinu',
  'back': 'Go Back',
  'next': 'Next',
  'skip': 'Skip am',
  'cancel': 'Kansul',
  'save': 'Save',
  'done': 'Don finish',
  'retry': 'Try again',
  'loading': 'E dey load...',
  'or_continue_with': 'Or use one of these',

  'home': 'Home',
  'search': 'Find',
  'bookings': 'Bookings',
  'profile': 'Me',
  'cart': 'Basket',

  'gs_title': 'You ready to enter inside?',
  'gs_subtitle_prefix': 'Join plenty Asaba people wey dey buy and book service for ',
  'gs_subtitle_suffix': ' today.',
  'gs_city': 'Asaba',
  'gs_start_shopping': 'Start to shop',
  'gs_register_vendor': 'Register as Seller',
  'gs_register_provider': 'Register to offer service',
  'gs_already_have_account': 'You don get account? ',
  'gs_log_in': 'Login',

  'lang_title': 'Choose your language',
  'lang_subtitle': 'Use MartoraX for the language wey\nsweet you pass.',
  'lang_select_appbar': 'Choose Language',

  'role_title': 'How you wan\njoin?',
  'role_subtitle': 'Pick the account wey suit wetin\nyou wan do for Asaba.',
  'role_shopper': 'Buyer',
  'role_shopper_desc': 'I wan dey buy goods and book service',
  'role_vendor': 'Seller',
  'role_vendor_desc': 'I wan sell goods',
  'role_provider': 'Service Person',
  'role_provider_desc': 'I wan offer my handwork',
  'role_rider': 'Rider',
  'role_rider_desc': 'I wan deliver and chop money',

  'login_welcome': 'Welcome back',
  'login_subtitle': 'Login enter your MartoraX account',
  'login_email': 'Email',
  'login_email_hint': 'name@example.com',
  'login_password': 'Password',
  'login_password_hint': 'Put password',
  'login_forgot': 'You forget password?',
  'login_btn': 'Login',
  'login_no_account': 'You no get account? ',
  'login_create_account': 'Open account',
  'login_enter_creds': 'Put email and password',
  'login_failed': 'Login no work. Check your network.',

  'reg_title': 'Open your account',
  'reg_subtitle': 'Join MartoraX make you fit buy and book service for Asaba.',
  'reg_full_name': 'Your Full Name',
  'reg_full_name_hint': 'John Doe',
  'reg_phone': 'Phone Number',
  'reg_btn': 'Sign Up',
  'reg_required': 'Name, email, and password dey required',
  'reg_password_short': 'Password must reach 6 letter',
  'reg_success': 'Account don open! Check your email make you verify.',
  'reg_failed': 'Signup no work. Check your network.',
  'reg_already_have_account': 'You don get account? ',
  'reg_login': 'Login',

  'location_label': 'WHERE YOU DEY',
  'location_value': 'Asaba, Delta State',
  'search_placeholder': 'Find market or work-person...',
  'market_clusters': 'Market Centres',
  'see_all': 'See All',
  'market_price_board': 'MARKET PRICE BOARD',
  'updated_today': 'E update today, 8:00 AM',
  'quick_services': 'Quick Handwork',
  'hot_deals': 'Cheapest Deals',
  'live': 'LIVE',

  'cart_title': 'My Basket',
  'cart_empty_title': 'Your basket empty',
  'cart_empty_subtitle': 'Add goods from any seller make you start.',
  'cart_start_shopping': 'Start to shop',
  'cart_clear': 'Clean basket',
  'cart_payment_summary': 'Wetin you go pay',
  'cart_items_total': 'Goods Total',
  'cart_delivery_fee': 'Delivery Money',
  'cart_safepay_fee': 'SafePay Money',
  'cart_total': 'Total',
  'cart_checkout_btn': 'Go Pay',
  'cart_added_suffix': ' don enter basket',
  'cart_view': 'OPEN BASKET',

  'profile_title': 'Me',
  'profile_preferences': 'WETIN I LIKE',
  'profile_language': 'Language',
  'profile_language_sub': 'English, Pidgin, Igbo...',
  'profile_notifications': 'Notifications',
  'profile_theme': 'App Theme',
  'profile_logout': 'Comot',

  'safepay_protection': 'SafePay Protection',
  'safepay_held_msg': 'SafePay go hold your money for 48 hours to settle fight. Your money dey safe while we check wetin happen.',
  'confirm_release': 'Confirm Release',
  'raise_dispute': 'Open Case',
  'raise_issue': 'Report wahala',
  'details_optional': 'More talk (If you like)',
  'what_is_problem': 'Wetin be the problem?',
  'upload_evidence': 'Put proof here',
  'evidence_hint': 'Put picture or video show wetin happen make we fit settle am fast-fast.',

  // Screen titles
  'st_admin_escrow': 'Escrow Dashboard',
  'st_admin_universal': 'Big Dashboard',
  'st_ai_feed': 'AI Feed For You',
  'st_ai_concierge': 'Service Helper',
  'st_ai_smart_quote': 'New Quote',
  'st_bookings': 'My Bookings',
  'st_checkout_confirm': 'Checkout',
  'st_checkout_delivery': 'Where We Go Bring Am',
  'st_checkout_payment': 'How You Wan Pay',
  'st_order_confirm': 'E Don Confirm',
  'st_group_buy_create': 'Open Group Buy Deal',
  'st_group_buy_invite': 'Group Buy Invite',
  'st_live_deals': 'Live Deals',
  'st_market_cluster': 'Market Centre',
  'st_market_hubs': 'Market Hubs',
  'st_market_trends': 'How Market Dey',
  'st_notifications': 'Notifications',
  'st_delivery_success': 'Delivery Don Land',
  'st_delivery_tracking': 'Track Order',
  'st_delivery_safety': 'Delivery Safety',
  'st_order_status': 'Order Status',
  'st_order_receipt': 'Look Your Receipt',
  'st_product_details': 'Product Details',
  'st_provider_leads': 'My Job List',
  'st_provider_nearby': 'Service Near Me',
  'st_provider_chat': 'Chat',
  'st_provider_dashboard': 'Service Dashboard',
  'st_provider_kyc': 'Confirm Say Na You',
  'st_provider_register': 'Register as Service Person',
  'st_service_profile': 'Service Page',
  'st_service_booking': 'Book Service',
  'st_service_discovery': 'Find Service',
  'st_provider_portfolio': 'Service Work',
  'st_quote_approval': 'Service Quote',
  'st_rider_earnings': 'My Money',
  'st_rider_in_transit': 'I Dey Move',
  'st_rider_register': 'Join as Rider',
  'st_rider_dashboard': 'Rider Dashboard',
  'st_rider_discovery': 'Find Rider',
  'st_search_filters': 'Sieve Am',
  'st_search': 'Find',
  'st_vendor_catalog': 'Basic Info',
  'st_vendor_dashboard': 'Seller Dashboard',
  'st_vendor_go_live': 'Go Live Setup',
  'st_vendor_inventory': 'Goods Inside',
  'st_vendor_kyc': 'Confirm Your Stall',
  'st_vendor_location': 'Where Shop Dey',
  'st_vendor_orders': 'Orders',
  'st_vendor_order_details': 'Order Details',
  'st_vendor_register': 'Register as Seller',
  'st_vendor_analytics': 'How Sales Dey',
  'st_escrow_dispute': 'Open Case',
  'st_wallet_history': 'History',
  'st_wallet_link_bank': 'Connect Bank',
  'st_wallet': 'Wallet & Bonus',
  'st_release_funds': 'Send Money',
  'st_delivery_rating': 'Rate Delivery',
  'st_product_bargain': 'Send Bargain',
  'st_onboarding': 'Welcome',

  // Splash
  'splash_connecting': 'WE DEY CONNECT ASABA',

  // Onboarding slides
  'onb_slide1_title': 'Find Everything\nfor Asaba',
  'onb_slide1_sub': 'From Ogbogonogo Main Market straight to your door. Sellers wey you fit trust dey for your hand.',
  'onb_slide2_title': 'Find Service People\nNear You',
  'onb_slide2_sub': 'Plumber, makeup artist, you name am. Book the people wey sabi work for Asaba.',
  'onb_slide3_title': 'Fast Delivery,\nSafe Payment',
  'onb_slide3_sub': 'SafePay go hold your money till delivery reach. You go track your order live from seller to your door.',

  // Search deeper
  'search_filter_nearest': 'Near Me',
  'search_filter_open': 'Open Now',
  'search_filter_cheap': 'Cheap Pass',
  'search_filter_trusted': 'Trusted',
  'search_tab_vendors': 'Sellers',
  'search_tab_services': 'Services',
  'search_tab_markets': 'Markets',
  'search_list': 'List',
  'search_map': 'Map',
  'search_visit_store': 'Enter Shop',
  'search_map_view': 'Map View',
  'search_map_coming': 'Google Maps go come soon',

  // Bookings deeper
  'bk_tab_upcoming': 'Coming Up',
  'bk_tab_completed': 'Don Finish',
  'bk_tab_cancelled': 'Kansul',
  'bk_empty': 'No book anything yet',

  // Checkout deeper
  'co_delivery_method': 'How Delivery Go Be',
  'co_home_delivery': 'Bring Am Come My House',
  'co_market_pickup': 'I Go Pick Am for Market',
  'co_address': 'Address',
  'co_address_hint': 'House no., street, area',
  'co_instructions': 'Direction (If you like)',
  'co_instructions_hint': 'Apartment, landmark, gate code...',
  'co_continue_to_pay': 'Kontinu Go Pay',
  'co_pay_card': 'Card',
  'co_pay_transfer': 'Bank Transfer',
  'co_pay_wallet': 'Wallet',
  'co_pay_continue': 'Kontinu',
  'co_order_summary': 'Order Summary',
  'co_place_order': 'Place Order',
  'co_payment_protected': 'SafePay Dey Hold Your Money',
  'co_confirmation_title': 'Order Don Enter!',
  'co_confirmation_sub': 'Dem dey arrange your order. We go message you when e ready.',
  'co_track_order': 'Track Order',
  'co_continue_shopping': 'Kontinu Shop',

  // Orders / tracking deeper
  'ord_status_placed': 'Order Don Enter',
  'ord_status_preparing': 'Dem Dey Arrange Am',
  'ord_status_shipped': 'E Don Comot',
  'ord_status_delivered': 'E Don Land',
  'ord_in_progress': 'E Dey Work',
  'ord_track_live': 'Live Tracking',
  'ord_call_rider': 'Call Rider',
  'ord_chat_rider': 'Chat Rider',
  'ord_eta': 'E Go Reach Around',
  'ord_delivered_title': 'Order Don Land!',
  'ord_rate_vendor': 'Rate Seller',
  'ord_rate_rider': 'Rate Rider',
  'ord_tip_rider': 'Drop Tip For Rider',
  'ord_leave_review': 'Drop Review',

  // Wallet deeper
  'wal_balance': 'Wetin Dey Wallet',
  'wal_topup': 'Add Money',
  'wal_withdraw': 'Comot Money',
  'wal_history': 'History',
  'wal_recent': 'Wetin Just Happen',
  'wal_cashback': 'Cashback Wey You Don Earn',
  'wal_promo_hint': 'Type promo code',
  'wal_apply': 'Apply Am',

  // Notifications deeper
  'ntf_mark_all_read': 'See all as read',
  'ntf_empty': 'No notification dey',

  // Product detail deeper
  'pd_quantity': 'How Many',
  'pd_description': 'Product Description',
  'pd_bargain': 'Bargain',
  'pd_add_to_cart': 'Add Am for Basket',
  'pd_visit_shop': 'Enter Shop',
  'pd_trusted': 'TRUSTED',

  // Profile deeper
  'prof_my_orders': 'My Orders',
  'prof_saved_addresses': 'Saved Address',
  'prof_payment_methods': 'How I Dey Pay',
  'prof_account': 'ACCOUNT',
  'prof_support': 'HELP',
  'prof_help_center': 'Help Centre',
  'prof_contact_support': 'Contact Help',
  'prof_terms': 'Terms & Privacy',
  'prof_become_vendor': 'Become Seller or\nService Person',
  'prof_become_sub': 'Start to sell or offer service for Asaba',
  'prof_get_started': 'Start',

  // Common actions
  'btn_submit': 'Send',
  'btn_save': 'Save',
  'btn_save_changes': 'Save Am',
  'btn_confirm': 'Confirm',
  'btn_go_back': 'Go Back',
  'btn_get_started': 'Start',
  'btn_proceed': 'Kontinu',
  'btn_pay_now': 'Pay Now',
  'btn_go_live': 'Go Live',
  'btn_add_product': 'Add Goods',
  'btn_submit_review': 'Drop Review',
  'btn_send': 'Send',
  'btn_book_now': 'Book Am',
  'btn_accept': 'Accept',
  'btn_reject': 'No, Reject',
};

// ---------------------------------------------------------------------------
// Igbo
// ---------------------------------------------------------------------------
const Map<String, String> _ig = {
  'app_title': 'MartoraX',
  'tagline': "Obodo Gị N'Akpa Gị",
  'continue': "Gaa n'ihu",
  'continue_btn': "Gaa n'ihu",
  'back': 'Laghachi',
  'next': 'Ọzọ',
  'skip': 'Wụgharịa',
  'cancel': 'Kagbuo',
  'save': 'Chekwaa',
  'done': 'Emechara',
  'retry': 'Nwaa ọzọ',
  'loading': 'Na-ebudata...',
  'or_continue_with': 'Maọbụ jiri otu n’ime ndị a',

  'home': 'Ụlọ',
  'search': 'Chọọ',
  'bookings': 'Ntinye akwụkwọ',
  'profile': 'Profaịlụ',
  'cart': 'Nkata',

  'gs_title': 'Ị dị njikere ịgagharị?',
  'gs_subtitle_prefix': 'Sonyere ọtụtụ ndị bi na-azụta ngwa ahịa na ndokwa ọrụ na ',
  'gs_subtitle_suffix': ' taa.',
  'gs_city': 'Asaba',
  'gs_start_shopping': 'Malite ịzụ ahịa',
  'gs_register_vendor': 'Debanye aha dị ka onye ahịa',
  'gs_register_provider': 'Debanye aha dị ka onye na-enye ọrụ',
  'gs_already_have_account': 'Ị nwere akaụntụ? ',
  'gs_log_in': 'Banye',

  'lang_title': 'Họrọ asụsụ gị',
  'lang_subtitle': "Jiri MartoraX n'asụsụ\nmasịrị gị karịa.",
  'lang_select_appbar': 'Họrọ Asụsụ',

  'role_title': 'Kedu ka ị ga-esi\nsonyere?',
  'role_subtitle': 'Họrọ ụdị akaụntụ kacha\nkọwaa mkpa gị na Asaba.',
  'role_shopper': 'Onye Na-azụ Ahịa',
  'role_shopper_desc': 'Achọrọ m ịzụ ngwa ahịa na ndokwa ọrụ',
  'role_vendor': 'Onye Na-ere Ahịa',
  'role_vendor_desc': 'Achọrọ m ire ngwa ahịa',
  'role_provider': 'Onye Na-enye Ọrụ',
  'role_provider_desc': 'Achọrọ m inye nka m',
  'role_rider': 'Onye Na-ebufe',
  'role_rider_desc': 'Achọrọ m ibu ngwa ma rite ego',

  'login_welcome': 'Nnọọ Ọzọ',
  'login_subtitle': 'Banye n’akaụntụ MartoraX gị',
  'login_email': 'Email',
  'login_email_hint': 'aha@example.com',
  'login_password': 'Okwuntughe',
  'login_password_hint': 'Tinye okwuntughe',
  'login_forgot': 'Chefuru Okwuntughe?',
  'login_btn': 'Banye',
  'login_no_account': 'Ị nweghị akaụntụ? ',
  'login_create_account': 'Mepee akaụntụ',
  'login_enter_creds': 'Tinye email na okwuntughe',
  'login_failed': 'Mbanye dara. Lelee njikọ gị.',

  'reg_title': 'Mepee Akaụntụ Gị',
  'reg_subtitle': 'Sonyere MartoraX iji zụta na debe ọrụ na Asaba.',
  'reg_full_name': 'Aha zuru ezu',
  'reg_full_name_hint': 'Chinedu Eze',
  'reg_phone': 'Nọmba ekwentị',
  'reg_btn': 'Debanye Aha',
  'reg_required': 'Aha, email, na okwuntughe dị mkpa',
  'reg_password_short': 'Okwuntughe ga-eru opekata mpe mkpụrụedemede isii',
  'reg_success': 'Akaụntụ emepere! Lelee email gị ka i kwado.',
  'reg_failed': 'Ndebanye aha dara. Lelee njikọ gị.',
  'reg_already_have_account': 'Ị nwere akaụntụ? ',
  'reg_login': 'Banye',

  'location_label': 'EBE Ị NỌ',
  'location_value': 'Asaba, Delta State',
  'search_placeholder': 'Chọọ ahịa ma ọ bụ ọrụ...',
  'market_clusters': 'Mpaghara Ahịa',
  'see_all': 'Hụ Niile',
  'market_price_board': 'BỌDỤ ỌNỤ AHỊA',
  'updated_today': 'Emelitere Taa, 8:00 AM',
  'quick_services': 'Ọrụ Ngwa Ngwa',
  'hot_deals': 'Ahịa Ndị Dị Mma',
  'live': 'LIVE',

  'cart_title': 'Nkata m',
  'cart_empty_title': 'Nkata gị tọgbọrọ chakoo',
  'cart_empty_subtitle': 'Tinye ngwa ahịa site n’aka onye ọzụzụ ọ bụla.',
  'cart_start_shopping': 'Malite ịzụ ahịa',
  'cart_clear': 'Hichapụ nkata',
  'cart_payment_summary': 'Nchịkọta Ụgwọ',
  'cart_items_total': 'Mkpokọta Ngwaahịa',
  'cart_delivery_fee': 'Ụgwọ Mbufe',
  'cart_safepay_fee': 'Ụgwọ SafePay',
  'cart_total': 'Mkpokọta',
  'cart_checkout_btn': 'Gaa Kwụọ Ụgwọ',
  'cart_added_suffix': ' agbakwunyere na nkata',
  'cart_view': 'LEE NKATA',

  'profile_title': 'Profaịlụ',
  'profile_preferences': 'IHE MASỊRỊ',
  'profile_language': 'Asụsụ',
  'profile_language_sub': 'English, Pidgin, Igbo...',
  'profile_notifications': 'Ọkwa',
  'profile_theme': 'Isiokwu Ngwa',
  'profile_logout': 'Pụọ',

  'safepay_protection': 'SafePay Nchebe',
  'safepay_held_msg': 'SafePay na-ejide ego gị ruo awa iri anọ na asatọ maka mkpebi. Ego gị dị na nchebe ka anyị na-eme nchọpụta.',
  'confirm_release': 'Hapụ Ego',
  'raise_dispute': 'Mee Mkpesa',
  'raise_issue': 'Kọọ wahala',
  'details_optional': 'Nkọwa ndị ọzọ (Nhọrọ)',
  'what_is_problem': 'Kedu ihe bụ nsogbu ahụ?',
  'upload_evidence': 'Bulite Ihe Akaebe',
  'evidence_hint': 'Tinye foto ma ọ bụ vidiyo na-egosi nsogbu ahụ maka mkpebi ngwa ngwa.',

  // Screen titles
  'st_admin_escrow': 'Dashboard Escrow',
  'st_admin_universal': 'Dashboard Niile',
  'st_ai_feed': 'AI Maka Gị',
  'st_ai_concierge': 'Onye Enyemaka Ọrụ',
  'st_ai_smart_quote': 'Quote Ọhụrụ',
  'st_bookings': 'Ndokwa M',
  'st_checkout_confirm': 'Kwụọ Ụgwọ',
  'st_checkout_delivery': 'Nkọwa Nnyefe',
  'st_checkout_payment': 'Ụzọ Ịkwụ Ụgwọ',
  'st_order_confirm': 'Nkwenye',
  'st_group_buy_create': 'Mepụta Mgbazinye Otu',
  'st_group_buy_invite': 'Ọkpụkpọ Mgbazinye',
  'st_live_deals': 'Ahịa Dị Ndụ',
  'st_market_cluster': 'Mpaghara Ahịa',
  'st_market_hubs': 'Ahịa Niile',
  'st_market_trends': 'Otú Ahịa Dị',
  'st_notifications': 'Ọkwa',
  'st_delivery_success': 'Nnyefe Gara Nke Ọma',
  'st_delivery_tracking': 'Nlekota Nnyefe',
  'st_delivery_safety': 'Nchekwa Nnyefe',
  'st_order_status': 'Ọnọdụ Iwu',
  'st_order_receipt': 'Lelee Akwụkwọ',
  'st_product_details': 'Nkọwa Ngwaahịa',
  'st_provider_leads': 'Ndepụta Ọrụ',
  'st_provider_nearby': 'Ọrụ Ndị Dị Nso',
  'st_provider_chat': 'Mkparịta Ụka',
  'st_provider_dashboard': 'Dashboard Ọrụ',
  'st_provider_kyc': 'Kwado Ndị Ị Bụ',
  'st_provider_register': 'Debanye Aha dị ka Onye Ọrụ',
  'st_service_profile': 'Profaịlụ Ọrụ',
  'st_service_booking': 'Debe Ọrụ',
  'st_service_discovery': 'Chọta Ọrụ',
  'st_provider_portfolio': 'Akwụkwọ Ọrụ',
  'st_quote_approval': 'Quote Ọrụ',
  'st_rider_earnings': 'Ego M',
  'st_rider_in_transit': 'Ana M Aga',
  'st_rider_register': 'Sonyere dị ka Rider',
  'st_rider_dashboard': 'Dashboard Rider',
  'st_rider_discovery': 'Chọta Rider',
  'st_search_filters': 'Nzacha',
  'st_search': 'Chọọ',
  'st_vendor_catalog': 'Nkọwa Bụ Isi',
  'st_vendor_dashboard': 'Dashboard Onye Ahịa',
  'st_vendor_go_live': 'Idobe Gaa Live',
  'st_vendor_inventory': 'Ngwaahịa',
  'st_vendor_kyc': 'Kwado Ụlọ Ahịa Gị',
  'st_vendor_location': 'Ebe Ụlọ Ahịa',
  'st_vendor_orders': 'Iwu',
  'st_vendor_order_details': 'Nkọwa Iwu',
  'st_vendor_register': 'Debanye Aha dị ka Onye Ahịa',
  'st_vendor_analytics': 'Nyocha Ọrụ Ahịa',
  'st_escrow_dispute': 'Mee Mkpesa',
  'st_wallet_history': 'Akụkọ na Akwụkwọ',
  'st_wallet_link_bank': 'Jikọọ Ụlọ Akụ',
  'st_wallet': 'Akpa Ego',
  'st_release_funds': 'Hapụ Ego',
  'st_delivery_rating': 'Nye Nnyefe Akara',
  'st_product_bargain': 'Zigara Bargain',
  'st_onboarding': 'Nnọọ',

  // Splash
  'splash_connecting': 'NA-EJIKỌTA ASABA',

  // Onboarding slides
  'onb_slide1_title': 'Chọta Ihe Niile\nna Asaba',
  'onb_slide1_sub': 'Site na Ogbogonogo Main Market ruo n’ọnụ ụzọ gị. Ndị na-ere ahịa ị nwere ike ịtụkwasị obi.',
  'onb_slide2_title': 'Chọta Ndị Nka\nDị Nso',
  'onb_slide2_sub': 'Site na ndị plumber ruo na ndị na-eme makeup. Debe ndị nka tụkwasịrị obi na Asaba.',
  'onb_slide3_title': 'Nnyefe Ngwa Ngwa\nNa Ịkwụ Ụgwọ Nchekwa',
  'onb_slide3_sub': 'SafePay na-ejide ego gị ruo mgbe ezitere. Lekota iwu gị na ndụ site n’aka onye ahịa ruo n’ọnụ ụzọ gị.',

  // Search deeper
  'search_filter_nearest': 'Nso Nso',
  'search_filter_open': 'Mepere Ugbu A',
  'search_filter_cheap': 'Onụ Ala Kacha',
  'search_filter_trusted': 'Eziokwu',
  'search_tab_vendors': 'Ndị Ahịa',
  'search_tab_services': 'Ọrụ',
  'search_tab_markets': 'Ahịa',
  'search_list': 'Ndepụta',
  'search_map': 'Map',
  'search_visit_store': 'Banye Ụlọ Ahịa',
  'search_map_view': 'Map',
  'search_map_coming': 'Google Maps na-abịa n’oge na-adịghị anya',

  // Bookings deeper
  'bk_tab_upcoming': 'Na-abịa',
  'bk_tab_completed': 'Emechara',
  'bk_tab_cancelled': 'Akagbuo',
  'bk_empty': 'Enwebeghị ndokwa',

  // Checkout deeper
  'co_delivery_method': 'Ụzọ Nnyefe',
  'co_home_delivery': 'Nnyefe N’Ụlọ',
  'co_market_pickup': 'Ana m Aga Were Ya',
  'co_address': 'Adreesị',
  'co_address_hint': 'Nọmba ụlọ, okporo ámá, mpaghara',
  'co_instructions': 'Ntuziaka (Nhọrọ)',
  'co_instructions_hint': 'Ụlọ, akara mmụta...',
  'co_continue_to_pay': 'Gaa Kwụọ Ụgwọ',
  'co_pay_card': 'Kaadị',
  'co_pay_transfer': 'Mbufe Ụlọ Akụ',
  'co_pay_wallet': 'Akpa Ego',
  'co_pay_continue': 'Gaa n’ihu',
  'co_order_summary': 'Nchịkọta Iwu',
  'co_place_order': 'Tinye Iwu',
  'co_payment_protected': 'SafePay Na-echebe Ụgwọ Gị',
  'co_confirmation_title': 'Iwu E Tinyere!',
  'co_confirmation_sub': 'A na-arụ iwu gị. Anyị ga-ezitere gị ọkwa.',
  'co_track_order': 'Lekota Iwu',
  'co_continue_shopping': 'Gaa n’ihu Zụọ',

  // Orders / tracking deeper
  'ord_status_placed': 'Iwu E Tinyere',
  'ord_status_preparing': 'A na-akwadebe',
  'ord_status_shipped': 'E zigara',
  'ord_status_delivered': 'E nyefere',
  'ord_in_progress': 'Na-aga n’ihu',
  'ord_track_live': 'Nlekota Ndụ',
  'ord_call_rider': 'Kpọọ Rider',
  'ord_chat_rider': 'Ozi Rider',
  'ord_eta': 'Oge Mberede',
  'ord_delivered_title': 'Iwu E Nyefere!',
  'ord_rate_vendor': 'Nye Onye Ahịa Akara',
  'ord_rate_rider': 'Nye Rider Akara',
  'ord_tip_rider': 'Nye Rider Onyinye',
  'ord_leave_review': 'Hapụ Nyocha',

  // Wallet deeper
  'wal_balance': 'Akpa Ego',
  'wal_topup': 'Tinye Ego',
  'wal_withdraw': 'Wepụta Ego',
  'wal_history': 'Akụkọ Azụmahịa',
  'wal_recent': 'Ihe Na-eme Ugbu A',
  'wal_cashback': 'Cashback Nweta',
  'wal_promo_hint': 'Tinye koodu promo',
  'wal_apply': 'Tinye',

  // Notifications deeper
  'ntf_mark_all_read': 'Mara niile dị ka agụrụ',
  'ntf_empty': 'Onweghị ọkwa ọhụrụ',

  // Product detail deeper
  'pd_quantity': 'Ole',
  'pd_description': 'Nkọwa Ngwaahịa',
  'pd_bargain': 'Bargain',
  'pd_add_to_cart': 'Tinye na Nkata',
  'pd_visit_shop': 'Banye Ụlọ Ahịa',
  'pd_trusted': 'EZIOKWU',

  // Profile deeper
  'prof_my_orders': 'Iwu m',
  'prof_saved_addresses': 'Adreesị Echekwara',
  'prof_payment_methods': 'Ụzọ Ịkwụ Ụgwọ',
  'prof_account': 'AKAỤNTỤ',
  'prof_support': 'ENYEMAKA',
  'prof_help_center': 'Ụlọ Enyemaka',
  'prof_contact_support': 'Kpọtụrụ Enyemaka',
  'prof_terms': 'Iwu na Nzuzo',
  'prof_become_vendor': 'Bụrụ Onye Ahịa ma ọ bụ\nOnye Ọrụ',
  'prof_become_sub': 'Bido ire ma ọ bụ inye ọrụ na Asaba',
  'prof_get_started': 'Bido',

  // Common actions
  'btn_submit': 'Nyefee',
  'btn_save': 'Chekwaa',
  'btn_save_changes': 'Chekwaa Mgbanwe',
  'btn_confirm': 'Kwado',
  'btn_go_back': 'Laghachi',
  'btn_get_started': 'Bido',
  'btn_proceed': 'Gaa n’ihu',
  'btn_pay_now': 'Kwụọ Ugbu A',
  'btn_go_live': 'Gaa Live',
  'btn_add_product': 'Tinye Ngwaahịa',
  'btn_submit_review': 'Nyefee Nyocha',
  'btn_send': 'Zipu',
  'btn_book_now': 'Debe Ugbu A',
  'btn_accept': 'Nakwere',
  'btn_reject': 'Jụ',
};

// ---------------------------------------------------------------------------
// Yoruba (partial — falls back to English for missing keys)
// ---------------------------------------------------------------------------
const Map<String, String> _yo = {
  'app_title': 'MartoraX',
  'tagline': 'Ilu Rẹ Ni Apo Rẹ',
  'continue_btn': 'Tẹsiwaju',
  'home': 'Ile',
  'search': 'Wa',
  'bookings': 'Awọn Iwe-kikọ',
  'profile': 'Profaili',
  'location_label': 'IBI TI O WA',
  'search_placeholder': 'Wa ọja tabi awọn iṣẹ...',
  'market_price_board': 'BỌDU AGBEGBE ỌJA',
  'updated_today': 'Imudojuiwọn Loni',
  'quick_services': 'Awọn Iṣẹ Yara',
  'hot_deals': 'Awọn Iṣowo Gbona',
  'live': 'LIVE',
  'safepay_protection': 'SafePay Idabobo',
  'safepay_held_msg': 'SafePay yoo di owo rẹ duro fun wakati 48 fun ipinnu. Awọn owo rẹ wa ni aabo lakoko ti a n ṣewadii.',
  'confirm_release': 'Jẹrisi Itusilẹ',
  'raise_dispute': 'Gbe Ariyanjiyan dide',
  'raise_issue': 'Jabo Isoro kan',
  'details_optional': 'Awọn alaye afikun (Aṣayan)',
  'what_is_problem': 'Kini isoro naa?',
  'upload_evidence': 'Po si Ẹri',
  'evidence_hint': 'Fi awọn fọto tabi awọn fidio ti o nfihan isoro naa han fun ipinnu yiyara.',
};

// ---------------------------------------------------------------------------
// Hausa (partial — falls back to English for missing keys)
// ---------------------------------------------------------------------------
const Map<String, String> _ha = {
  'app_title': 'MartoraX',
  'tagline': 'Garin Ku A Cikin Aljihunku',
  'continue_btn': 'Ci gaba',
  'home': 'Gida',
  'search': 'Bincika',
  'bookings': 'Littattafan Ayyuka',
  'profile': 'Profile',
  'location_label': 'WURIN DA KUKE',
  'search_placeholder': 'Bincika kasuwanni ko ayyuka...',
  'market_price_board': 'HUKUMAR FARASHIN KASUWA',
  'updated_today': 'An sabunta yau',
  'quick_services': 'Ayyuka Masu Sauri',
  'hot_deals': 'Mafi Kyawun Kasuwanci',
  'live': 'LIVE',
  'safepay_protection': 'SafePay Kariya',
  'safepay_held_msg': "SafePay zai riƙe kuɗin ku na tsawon sa'o'i 48 don warware matsala. Kuɗaɗen ku suna cikin aminci yayin da muke bincike.",
  'confirm_release': 'Tabbatar da Sakewa',
  'raise_dispute': 'Tada Rigima',
  'raise_issue': 'Bada Rahoton Matsala',
  'details_optional': 'Ƙarin cikakkun bayanai (Na zaɓi)',
  'what_is_problem': 'Menene matsalar?',
  'upload_evidence': 'Shigar da Hujja',
  'evidence_hint': 'Haɗa hotuna ko bidiyo da ke nuna matsalar don yanke shawara mai sauri.',
};
